import type { Metadata } from "next";
import { Geist, Geist_Mono, Alexandria, Montserrat } from "next/font/google";
import "./globals.css";

import Header from "./Components/Header";
import Footer from "./Components/Footer";
import MobileHeader from "./Components/MobileHeader";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const alexandria = Alexandria({subsets: ["latin"], weight: ["400", "700"]});
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const montserrat = Montserrat({subsets: ["latin"], weight: ["400", "700"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={` antialiased font-light ${montserrat.className}`}
      >
        <Header />
        <MobileHeader/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
